version: '3.7'
services:
  web:
    build:
      context: ./xnat
      args:
        XNAT_DATASOURCE_DRIVER: ${XNAT_DATASOURCE_DRIVER}
        XNAT_DATASOURCE_URL: ${XNAT_DATASOURCE_URL}
        XNAT_DATASOURCE_USERNAME: ${XNAT_DATASOURCE_USERNAME}
        XNAT_DATASOURCE_PASSWORD: ${XNAT_DATASOURCE_PASSWORD}
        XNAT_HIBERNATE_DIALECT: ${XNAT_HIBERNATE_DIALECT}
        TOMCAT_XNAT_FOLDER: ${TOMCAT_XNAT_FOLDER}
        XNAT_ROOT: ${XNAT_ROOT}
        XNAT_HOME: ${XNAT_HOME}
    command: ["catalina.sh", "jpda", "run"]
    restart: always
    ports:
        - 8100:8080
        - 8101:8000
    volumes:
      - /extra/xnat/plugins:/data/xnat/home/plugins
      - /extra/xnat/data/logs:/data/xnat/home/logs
      - /extra/xnat/data/archive:/data/xnat/archive
      - /extra/xnat/data/build:/data/xnat/build
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - xnat-db
    environment:
      - CATALINA_OPTS=-Xms${XNAT_MIN_HEAP} -Xmx${XNAT_MAX_HEAP} -Dxnat.home=${XNAT_HOME} # -Dcom.sun.management.jmxremote= -Dcom.sun.management.jmxremote.port=1099 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=127.0.0.1

  xnat-db:
    image: postgres:13-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: xnat
      POSTGRES_PASSWORD: xnat
      POSTGRES_DB: xnat
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "xnat"]
      interval: 5s
      retries: 5
    restart: always
