version: '3.7'
services:
  web:
    build:
      context: ./xnat
      args:
        XNAT_VER: ${XNAT_VER}
        XNAT_DATASOURCE_DRIVER: ${XNAT_DATASOURCE_DRIVER}
        XNAT_DATASOURCE_URL: ${XNAT_DATASOURCE_URL}
        XNAT_DATASOURCE_USERNAME: ${XNAT_DATASOURCE_USERNAME}
        XNAT_DATASOURCE_PASSWORD: ${XNAT_DATASOURCE_PASSWORD}
        XNAT_HIBERNATE_DIALECT: ${XNAT_HIBERNATE_DIALECT}
        TOMCAT_XNAT_FOLDER: ${TOMCAT_XNAT_FOLDER}
        XNAT_ROOT: ${XNAT_ROOT}
        XNAT_HOME: ${XNAT_HOME}
    ports:
        - 8100:8080
    volumes:
      - /extra/xnat/plugins:/data/xnat/home/plugins
      - /extra/xnat/data/logs:/data/xnat/home/logs
      - /extra/xnat/data/archive:/data/xnat/archive
      - /extra/xnat/data/build:/data/xnat/build
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - xnat-db
    environment:
      - CATALINA_OPTS=-Xms${XNAT_MIN_HEAP} -Xmx${XNAT_MAX_HEAP} -Dxnat.home=/data/xnat/home
      - XNAT_HOME=/data/xnat/home

  xnat-db:
    image: postgres:13-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: xnat
      POSTGRES_PASSWORD: xnat
      POSTGRES_DB: xnat
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "xnat"]
      interval: 5s
      retries: 5
    restart: always
