version: '2'
services:
  web:
    build:
      context: ./xnat
      args:
        XNAT_VER: 1.7.6
        XNAT_DATASOURCE_DRIVER: org.postgresql.Driver
        XNAT_DATASOURCE_URL: "jdbc:postgresql://postgres/xnat"
        XNAT_DATASOURCE_USERNAME: xnat
        XNAT_DATASOURCE_PASSWORD: xnat
        XNAT_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQL9Dialect
        TOMCAT_XNAT_FOLDER: ROOT
        XNAT_ROOT: /data/xnat
        XNAT_HOME: /data/xnat/home
    ports:
      - 8100:8080
    volumes:
      - /extra/xnat/plugins:/data/xnat/home/plugins
      - /extra/xnat/data/logs:/data/xnat/home/logs
      - /extra/xnat/data/archive:/data/xnat/archive
      - /extra/xnat/data/build:/data/xnat/build
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - xnat-db
    environment:
      - CATALINA_OPTS=-Xms256m -Xmx2g -Dxnat.home=/data/xnat/home
      - XNAT_HOME=/data/xnat/home

  xnat-db:
    build: ./postgres
    expose:
      - "5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${XNAT_DATASOURCE_ADMIN_PASSWORD}
